### PR TITLE
Replace ListView to FlatList about picker dialogs

### PR DESCRIPTION
**Pull request by sasurau4**
This PR deal with https://github.com/hectahertz/react-native-material-dialog/issues/47.

## Notes
I carefully refactor ListView to FlatList not to break any styles and api interfaces.
So, I tested about following items about this PR.

- no change of apperance.
- no change of api interface.
- 1000 items rendered fine on dialog.

My test environment.
```
node: v11.0.0
OS: Ubuntu 18.04
Mobile OS: Android 8.1, emulator
react-native: 0.57.4
react: 16.6.0-alpha.8af6728
```

I mainly refer to [react-native docs](https://facebook.github.io/react-native/docs/flatlist).

### CODE REVIEW

**Comment by iamdarknight** [comment]
ListView is now giving warnings of deprecation, please merge this branch once its ready. Thank you!!

**Comment by Boubaker93** [comment]
Hello is this branch got merged correctly ? because the last version of material-dialog (0.7.6) still gives warning about ListView

**Comment by JonBerglund** [comment]
Any news on this merge?
ListView is deprecated and cant be used within the new react-native version.

**Comment by Boubaker93** [comment]
@JonBerglund feels like they are not gonna update this lib... i just forked it and accepted @sasurau4's PR in my branch.
It works fine now (thanks @sasurau4).

**Comment by hectahertz** [comment]
Thanks a lot for the contribution @sasurau4 ! 👏🏻

**Pull request merged**
